# Generated by Django 3.1.5 on 2021-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20210425_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='webpage/images/items/'),
        ),
    ]
