# Generated by Django 3.1.5 on 2021-04-28 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0012_auto_20210426_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateTimeField(default=django.utils.timezone.now)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.bid')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.item')),
                ('user', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
